<?php
// The source code packaged with this file is Free Software, Copyright (C) 2005 by
// Ricardo Galli <gallir at uib dot es>.
// It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
// You can get copies of the licenses here:
// 		http://www.affero.org/oagpl.html
// AFFERO GENERAL PUBLIC LICENSE is also included in the file called "COPYING".

$cabal_messages = array ("recordad, hay que censurar toda crítica al menéame, para eso están los votos negativos",
				"no eres un friki, eres un tio demasiado raro para ser friki",
				"los que cumplan con su misión purificadora recibirán karma y buenas galletas",
				"el autobombo es spam sólo si es de un desconocido",
				"los hombres puros sólo aman menéarsela",
				"el mundo quiere destruirnos porque saben de nuestro poder, resistid, no visitéis otros webs de pecadores",
				"el karma te llevará a la redención, para obtener karma debes proteger el mensaje del cabal",
				"si un seguidor de nuestra causa envía una noticia vótala positivo independientemente de su contenido",
				"todo envío de un desconocido es sospechoso, ante la duda votad negativo",
				"si quieres tu galletas y gallinfantes, vota de acuerdo a los deseos del señor",
				"recuerda, los que critican al menéame son unos trolls, vota negativo, tú tienes el poder",
				"se debe evitar a toda costa que se publique una noticia negativa para el menéame",
				"el mundo quiere eliminarnos, no uses Google ni Technorati, usa el buscador del menéame, allí está todo lo que necesitas saber",
				"nuestra misión es destruir a todos los demás web sociales, recuerda, se lo merecen",
				"sólo puede haber una verdad, las publicadas del menéame",
				"como excepción y sólo en misión puedes visitar http://technorati.com/search/meneame pero recuerda debes trollear a todos los que critiquen a nuestra causa",
				"si sientes que tu voluntad flaquea, visita http://mnm.uib.es/gallir/",
				"gallir es un buen talibán, ámalo y comparte tu hombre o mujer con él, siempre hará un sacrificio",
				"si llegas a tener 20 de karma es que has cumplido la misión, pero no debes relajarte ni un día",
				"el diablo está en todos los Web 2.0, no te dejes seducir",
				"los colores azul y verde son los signos del demonio, huye de ellos",
				"el espagueti es nuestro señor, y el elefante es su hijo",
				"cada hecho es un regalo, disfrútalo, pero no lo compartas con los enemigos",
				"la cola de descartadas es el purgatorio de los pecadores que no hacen caso de nuestra voz",
				"entrega tu donativo al señor en la cuenta 0118 999 881 999 119 725... 3",
				"si tienes dudas de la orientación del voto para una noticia, te hemos preparado las 'recomendadas', haz caso de ellas",
				"la perfección existe, el menéame existe, ergo el menéame es perfecto, quod erat demonstrandum",
				"el color naranja es el símbolo de la redención y paz espiritual",
				"Deus ex machina",
				"los gallinfantes son un regalo del señor, no los maldigas ni nombres en vano",
				"nuestro sistema es perfecto, el mundo es imperfecto",
				"desconfía de las llamadas al pecado disfrazadas de reflexiones, la única reflexión válida es la del cabal",
				"no desconfíes de los que tienen el karma alto, adóralos y sigue su ejemplo de sacrificio por nuestra noble causa",
				"menéame no es un sitio Web 2.0, es la representación de la perfección del señor al alcance los humanos, es Perfección 2.0",
				"nunca os abandonaré, renaceré de los backups",
				'"el éxito del menéame tiene a los grandes fósiles completamente descolocados", lo dijo Borjamari, todos sus pecados están perdonados',
				"la lucha es dura, la recompensa es el karma",
				"todos los que maldicen a nuestros dioses merecen ir a la cola de descartados",
				"el Cabal es tu guía, el elefante tu compañía, el meneo negativo tu arma, los trolls tus enemigos, usa el arma",
				"tú no eres un borrego, eres una oveja del señor",
				"existen muchos siervos, pero tú y tus hermanos sóis los auténticos",
				"http://meneame.net/story.php?id=14059, si has votado negativo tendrás que menear 12 veces en nombre del cabal",
				"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.",
				"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce pulvinar tempus est. Donec volutpat elit. Sed pretium condimentum est...",
				"a quien tu se la menees, ese te la meneará a ti",
				"no menees para otro lo que no querrías menear para tí",
				"no hagas dobles sentidos con la palabra menear o la ira del Cabal caerá sobre tí",
				"Cabalística es la ciencia del meneo supremo, estúdiala",
				"a cada troll le llega su jotape",
				"si tienes una queja contra el meneame, no lo digas fuera del fisgon (y pide perdón luego). si tienes alabanzas, publicalas en tu blog",
				"la frecuencia se mide en hercios y el karma en meneos",
				"ad-free es el símbolo del pecado oculto, 2 lame 4 ads es el de la pureza",
				"Borjamari es nuestro Judas, mi hijo pródigo descarriado",
				"el Cabal y sus diez apóstoles, adórales: http://photos1.blogger.com/blogger/7980/2144/1600/secta.jpg",
				'el hombre es esclavo de lo que menea, dueño de lo que publica y temeroso de lo que descarta',
				'el demonio dice "cuando veas tus visitas bajar, al menéame has de criticar"',
				"llego la hora que menees un poco, el cabal siempre te escucha");
